# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.CharField(default='image_source', max_length=30),
        ),
    ]
